dashboard:
    path:     /
    defaults: { _controller: FactureBundle:Default:index }

tva:
    path:     /ref/tva/{id}
    defaults: { _controller: FactureBundle:Default:tva,id:null }
    
delete_tva:
    path:     /delete_tva/{id}
    defaults: { _controller: FactureBundle:Default:tvaDelete }

produit:
    path:     /ref/produit/{id}
    defaults: { _controller: FactureBundle:Default:produit,id:null }
    
delete_produit:
    path:     /delete_produit/{id}
    defaults: { _controller: FactureBundle:Default:produitDelete }

user:
    path:     /ref/user/{id}
    defaults: { _controller: FactureBundle:Default:user,id:null }
    
delete_user:
    path:     /delete_user/{id}
    defaults: { _controller: FactureBundle:Default:userDelete }
    
enabled_user:
    path:     /enableUser/{id}
    defaults: { _controller: FactureBundle:Default:enableUser }
    
entete:
    path:     /facture/ajouter
    defaults: { _controller: FactureBundle:Default:addEntete }    
    
liste:
    path:     /facture
    defaults: { _controller: FactureBundle:Default:listeEntete }    
    
addligne:
    path:     /facture/{id}/ligne/{ligne}
    defaults: { _controller: FactureBundle:Default:addLigne,ligne:null }  
    
deleteLigne:
    path:     /delete/{id}
    defaults: { _controller: FactureBundle:Default:deleteLigne }  

valider:
    path:     /valider/{id}
    defaults: { _controller: FactureBundle:Default:valider }  

annuler:
    path:     /annuler/{id}
    defaults: { _controller: FactureBundle:Default:annuler }  

print:
    path:     /facture/{id}/print
    defaults: { _controller: FactureBundle:Default:print }  