facture:
    resource: "@FactureBundle/Resources/config/routing.yml"
    prefix:   /

ajax:
    resource: "@FactureBundle/Resources/config/ajax.yml"
    prefix:   /ajax

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"